mod errors1;

use self::errors1::run_errors1;

fn main() {
    run_errors1();
}
